### ISSUE TITLE
This Addons broken to 16.3.31 updates

### ISSUE THREAD

**Issue by ghost** [wyozi/wmc-plus#16]
[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

loop to console message...

**Comment by wyozi** [comment]
Fixed by wyozi/gmod-medialib@d14edd528

wmc-plus update pending..
