### ISSUE TITLE
scriped error with new update 

### ISSUE THREAD

**Issue by chrisvsbeth** [wyozi/wmc-plus#18]
[ERROR] lua/wmcp_libs/medialib.lua:1179: attempt to index local 'err' (a nil value)
1. unknown - lua/wmcp_libs/medialib.lua:1179
   1. include_cl - [C]:-1
   2. include_sh - lua/autorun/wmcplus.lua:11
      1. unknown - lua/autorun/wmcplus.lua:15

no clue why the last bulds worked fine

**Comment by wyozi** [comment]
The line of code in that error does not seem to match the line in current revision of medialib included with wmcp. I updated the workshop, let me know if the error still happens.

**Comment by chrisvsbeth** [comment]
yes that did the trick thanks
