### ISSUE TITLE
It doesn't work as intended all of sudden!

### ISSUE THREAD

**Issue by dpaci** [wyozi/wmc-plus#23]
I made an Issue thread in the old addon because I thought it was the one, turns out I actually have WMC+ installed :)

Hey, it's a great addon and I along with my players love using it for my server. Though recently, while I didn't do ANY change to the addon's content, I found out that when I press "Play" or "Play globally" on a song it would load but doesn't start I guess. I enabled the video and all I get is a black screen.

Also I noticed that I can't remove the songs from the in-game menu unless I manually remove them from /data/wmcp.txt

Thanks for reading!

**Comment by wyozi** [comment]
The latest workshop or github version should work. Are you sure your copy is up to date?

**Comment by dpaci** [comment]
​Thanks for the instant answer! I updated it today and everything works
intended, thanks. Guess it was a stupid error on my side :S

By the way, I also have the TTT utilities installed, and when I right click
on a Song I also have the Players and SteamID options. What do they do?

**Comment by wyozi** [comment]
I believe they set player- specific end round music. Been a while since I looked into that codebase though.
